spring.application.name=jornada-da-terra

# Banco H2 em memória (ideal para entrega acadêmica)
spring.datasource.url=jdbc:h2:mem:jornadadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Porta
server.port=8080
